apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: papertrade
  labels:
    app.kubernetes.io/name: papertrade
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: papertrade
      app.kubernetes.io/component: api
