apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papertrade-data
  labels:
    app.kubernetes.io/name: papertrade
    app.kubernetes.io/component: content-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
