apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: papertrade-prod

resources:
  - ../../base

images:
  - name: papertrade
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/papertrade
    newTag: local
